name: A workflow for my Hello World file
on: push

jobs:
  build:
    name: Hello world action
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: ./action-a
        with:
          MY_NAME: "Mona"
  comment-on-pr:
    name: 'Comment PR'
    uses: actions/github-script@0.3.0
    if: github.event_name == 'pull_request'
    with:
      github-token: ${{ secrets.GITHUB_TOKEN }}
      script: |
        const { issue: { number: issue_number }, repo: { owner, repo }  } = context;
        github.issues.createComment({ issue_number, owner, repo, body: 'Hello world ! 👋' });