name: A workflow for my Hello World file
on: push

jobs:
  build:
    name: Hello world action
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: ./action-a
        with:
          MY_NAME: "Mona"
  
      - name: Actions Ecosystem Create Comment
        uses: actions-ecosystem/action-create-comment@v1.0.0
        with:
          github_token: ${{ secrets.github_token }}
          body: |
            Hello world @${{ github.actor }} 👋!


        
